# Wallpaper
output * bg $wallpaper fill

# Monitor
output "LVDS-1" {
    resolution 1366x768@60.009Hz
    position 0,0
    scale 1.0
}

# Keyboard
input "type:keyboard" {
    xkb_layout "us"
    xkb_options "grp:win_space_toggle"
}