# Mouse behavior
focus_follows_mouse no
mouse_warping none
focus_wrapping no
seat * hide_cursor 10000

# Marks
for_window [app_id="(?i)firefox"] mark Browser
for_window [app_id="(?i)code"]    mark Code
for_window [class="(?i)discord"]  mark Discord
for_window [class="(?i)spotify"]  mark Spotify
for_window [class="(?i)vlc"]      mark VLC

# Window workspace assignment