# Mouse behavior
focus_follows_mouse no
mouse_warping none
focus_wrapping no
seat * hide_cursor 10000

# Disable urgent
focus_on_window_activation none

# Application startup behavior
for_window {
    # Workspace 0
    # [app_id="kitty"]   ...
    
    # Workspace 1
    [app_id="code-oss"]  move container to workspace $ws1
    
    # Workspace 2
    [app_id="firefox"]   move container to workspace $ws2, focus
    
    # Workspace 3
    [app_id="discord"]   move container to workspace $ws3, focus
    
    # Workspace 4
    [class="Spotify"]    move container to workspace $ws4
    
    # Workspace 5
    [class="vlc"]        move container to workspace $ws5, focus
}
# Daemons
for_window [app_id="xdg-desktop-portal-gtk"] resize set width 70ppt height 80ppt