# Switch to workspace
bindsym $mod+grave workspace number $ws0
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9

# Cycle workspaces
bindsym $mod+Tab workspace back_and_forth
bindsym $mod+Shift+Tab workspace next_on_output
bindsym $mod+g layout toggle all

# Send focused window to workspace
bindsym $mod+Shift+grave move container to workspace number $ws0
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9

# Focus window
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# Move focused window
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right


# Window splitting
bindsym $mod+bracketleft splith
bindsym $mod+bracketright splitv

# Window functions
bindsym $mod+f fullscreen
bindsym $mod+p focus parent
bindsym $mod+q kill
bindsym $mod+Shift+q focus parent, kill

# Sway functions
bindsym $mod+Shift+e exit
bindsym $mod+Shift+r reload
bindsym $mod+minus opacity minus $opacity_notch
bindsym $mod+equal opacity plus $opacity_notch
bindsym $mod+Shift+minus opacity set 0.00
bindsym $mod+Shift+equal opacity set 1.00

# Floating windows
bindsym $mod+Shift+Space floating toggle, resize set 70ppt 80ppt
floating_modifier $mod normal


# Launch keybinds
# System
bindsym $mod+a exec $term
bindsym $mod+w exec $apps
bindsym $mod+e exec $files
bindsym $mod+Escape exec $lock

# Application
bindsym $mod+b exec $browser
bindsym $mod+n exec $incognito
bindsym $mod+c exec $code
bindsym $mod+Shift+c exec $code_debug
bindsym $mod+v exec $vlc
bindsym $mod+d exec $discord
bindsym $mod+s exec $music


# Power options
bindsym $mod+F3 exec systemctl suspend
bindsym $mod+F4 exec systemctl poweroff
bindsym $mod+F5 exec systemctl reboot


# Other
bindsym $mod+z [con_mark="TEST"] focus