# Waybar
font pango: Maple Mono Bold 10
# bar {
#   swaybar_command waybar
# }
bar {
    position top

    status_command while date +'%Y-%m-%d %X'; do sleep 1; done

    colors {
        statusline #ffffff
        background #323232
        inactive_workspace #32323200 #32323200 #5c5c5c
    }
}

# Gaps
smart_gaps on
gaps inner 5
gaps outer -5

# Borders
smart_borders on
default_border pixel 2
default_floating_border pixel 2


# Color scheme            border        background     text        indicator     child border
client.focused            #0ee523     #00000000    #0ee523   #0ee523     #0ee523