# Waybar
font pango: Maple Mono Bold 10
# bar {
#   swaybar_command waybar
# }
bar {
    position top

    status_command while date +'%Y-%m-%d %X'; do sleep 1; done

    colors {
        statusline #ffffff
        background #323232
        inactive_workspace #32323200 #32323200 #5c5c5c
    }
}

# Gaps
smart_gaps on
gaps inner 5
gaps outer -5

# Borders
smart_borders on
default_border pixel 2
default_floating_border pixel 2

# Color Scheme
set $fc     #0ee523
set $unfc   #00000000
set $unfc2  #00000000
set $urg    #ff0202

#                         border   bg       text  ind     child border
client.focused            $fc      $unfc2   $fc   $fc     $fc
client.focused_inactive   $unfc    $unfc2   $fc   $unfc   $unfc
client.unfocused          $unfc    $unfc2   $fc   $unfc   $unfc
client.urgent             $urg     $unfc2   $fc   $urg    $urg