# System variables
set $mod Mod4

# Workspaces
set $ws1 1
set $ws2 2
set $ws3 3
set $ws4 4
set $ws5 5
set $ws6 6
set $ws7 7
set $ws8 8
set $ws9 9
set $ws10 10

# System applications
set $term kitty
set $apps pgrep wofi >/dev/null 2>&1 && killall wofi || wofi --show drun
set $lock gtklock
set $files nautilus

set $browser firefox --new-tab
set $incognito $browser --private-window
set $code code
set $code_debug code --disable-extensions
set $vlc vlc > /dev/null 2>&1
set $discord discord > /dev/null 2>&1
set $music spotify > /dev/null 2>&1

# Other
set $wallpaper ~/.config/Wallpaper.jpg